name: Generate Errors SDK
on:
  push:
    branches:
      - main
    paths:
      - "packages/**"

jobs:
  generateErrors:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Fetch Errors JSON files
        run: ./scripts/fetch-errors.sh
      - name: Generate Errors SDK
        run: ./scripts/generate-errors.sh
      - uses: peter-evans/create-pull-request@v3
        with:
          title: "fix(all): regenerated Error SDK(s)"
          token: "${{ secrets.CI_USER_TOKEN }}"
          commit-message: "fix(all): regenerated Error SDK(s)"
          author: "app-services-ci <app-services-ci@users.noreply.github.com>"
          branch: chore/generate-sdks-errors
          branch-suffix: timestamp
          reviewers: craicoverflow, wtrocki
          delete-branch: true
          body: |
            _This pull request was auto-generated_

            This PR adds the latest generated ERROR SDKs .

            **Actions**:

              1. Review changes
              2. Approve and merge.
              3. Create a release if needed